server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  main:
    allow-circular-references: true
  application:
    name: pilotes
  datasource:
    url: jdbc:h2:mem:pilotes
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
app:
  pilotes:
    single-price: 1.33